[package]
name = "benchmarks"
version = "0.1.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[dependencies]
executor = { path = "../executor" }
primitives = { path = "../primitives" }
runtime = { path = "../runtime" }
state = { path = "../state" }
